### ISSUE TITLE
AppleSignin.authorize() produces an OK alert dialog instead of showing apple sign in screen

### ISSUE THREAD

**Issue by khehrarajbirgaa** [tidev/titanium-apple-sign-in#15]
Hi,
 
We are getting an issue with apple sign in. AppleSignin.authorize() produces an OK alert dialog instead of showing apple sign in screen. Can you please help?
 
Below are some details:
 
To integrate apple sign we performed the following steps.
 
1. Installed the ti.applesignin module
 
2. Added the entitlement section to tiapp.xml
-------------------------------
 <entitlements>
      <dict>
        <key>com.apple.developer.applesignin</key>
        <array>
          <string>Default</string>
        </array>
      </dict>
    </entitlements>
------------------------------------
3.  added the following code
------------------------------------------------
var AppleSignIn = require('ti.applesignin');
 
AppleSignIn.addEventListener('login', function (event) {
 Ti.API.warn(event.error);
 console.warn(`loginevent: ${JSON.stringify(event, null, 2)}`);
 if (!event.success) {
   alert(event.error);
   return;
 }
 
  Ti.API.warn(event);
});
 
var win = Ti.UI.createWindow({
  backgroundColor: '#fff'
});
 
var btn = AppleSignIn.createLoginButton({ width: 280, height: 38 });
 
btn.addEventListener('click', function () {
  AppleSignIn.authorize();
});
 
win.add(btn);
win.open();  
---------------------------------------------------------------
4. Enabled the sign in option in provisioning profile on https://developer.apple.com/ and downloaded and installed that provisioning profile to run our app.
 
Titanium SDK version: 8.3.0
 
The "Sign In" button shows up but on clicking it gives only ‘OK’.
 
The event object logs show success: false and cancelled: true and there is no error field (see log below):
 
loginevent: {
[WARN] :     "success": false,
[WARN] :     "cancelled": true,
[WARN] :     "bubbles": true,
[WARN] :     "type": "login",
[WARN] :     "source": {},
[WARN] :     "cancelBubble": false
[WARN] :   }

**Comment by hansemannn** [comment]
It does, because `event.error` can be undefined, since it is managed through success true/false, resulting in an alert without a message => `OK` only.

**Comment by khehrarajbirgaa** [comment]
Why did the login screen from Apple login screen not show up on button click?am I missing something?

**Comment by janvennemann** [comment]
@khehrarajbirgaa If you take a closer look at the event data, you can see that `cancelled: true` is set. This either means that the user canceled the login request or that it failed with an unknown error due to wrong configuration. I'd suggest to check your device logs using Console app for more infos about what might be going wrong.
