### ISSUE TITLE
Error when calling AppleSignIn.authorize()

### ISSUE THREAD

**Issue by brentonhouse** [tidev/titanium-apple-sign-in#5]
```
iOS 13 GM
SDK 8.2.0.RC
Xcode 11 GM
```

Using the sample code provided:

```
var AppleSignIn = require('ti.applesignin');

AppleSignIn.addEventListener('login', function (event) {
  if (!event.success) {
    alert(event.error);
    return;
  }

  Ti.API.warn(event);
});

var win = Ti.UI.createWindow({
  backgroundColor: '#fff'
});

var btn = AppleSignIn.createLoginButton({ width: 280, height: 38 });

btn.addEventListener('click', function () {
  AppleSignIn.authorize();
});

win.add(btn);
win.open();
```

I am getting an error: 
```
The operation couldn’t be completed. 
(com.apple.AuthenticationServices.AuthorizationError error 1000.
```
The function `AppleSignIn.authorize()` is immediately triggering the `login` event where the error is the caught.

![IMG_3338](https://user-images.githubusercontent.com/1746718/64833515-e92df700-d5a3-11e9-9318-862d11ee5ece.jpg)

**Comment by hansemannn** [comment]
Either you are missing the entitlements or your provisioning profile does not include the sign in capability (re-generate online) or your device has no Apple ID associated (which I think should be a different error).

**Comment by m1ga** [comment]
Having the same error. 
I have a `dev` (wildcard; can't switch sign-in on there) certificate and a `app dev` (matching my bundle id) certificate with sign-in capability. Where can I see which certificate is used for the simulator?
I've also logged into my simulators iCloud but still there is this error message.

**Comment by brentonhouse** [comment]
@m1ga - I ended up using a non-wildcard cert.   I updated the steps I did here, if it helps you at all:  https://github.com/brentonhouse/titanium-applesignin/blob/master/readme.md

**Comment by m1ga** [comment]
@brentonhouse ~that fork is private?~ now it's working. Testing your steps!
I've removed the wildcard dev certificate out of the prov.prof. folder, restarted the simulator and cleaned my project but the error still shows up

**Comment by brentonhouse** [comment]
sorry, made it public now.

Are you using both a non-wildcard App ID and a non-wildcard Provisioning Profile?

**Comment by m1ga** [comment]
my non-wildcard matches the bundle identifier and I've removed the wildcard one. But I just saw that there is a "Sign in with apple" configuration I still have to fill out (register domains, email) under "more". Is that need for testing already?

**Comment by brentonhouse** [comment]
Not sure.  I did add my gmail address in the second section of this but didn't add any domains.   If this is a required part, I need to add that to the documentation as well.

**Comment by brentonhouse** [comment]
I tried removing the email address I had previously added, reset simulator, and rebuilt app.  The signin still worked

**Comment by m1ga** [comment]
I removed all my profiles and just installed the new prov.profile I've created with `sign-in` switched on:
![Screenshot_20190914_190359](https://user-images.githubusercontent.com/4334997/64911486-b5c5a680-d722-11e9-82d4-79839b9a083e.png)
still shows that error. But good to know that the email/domain is not need for testing

**Comment by m1ga** [comment]
Ah, found the solution! My fault: I've put the `<entitlements>` block inside  `plist` - `dict` where all other key/string values are! 

Moving it below `</plist>` just inside the `<ios>` block worked! Maybe you could add it like this to the readme:

```xml
<ios>
     <plist>
         <!-- ... -->
     </plist>
     <entitlements>
        <dict>
          <key>com.apple.developer.applesignin</key>
          <array>
              <string>Default</string>
          </array>
        </dict>
      </entitlements>
</ios>
```

**Comment by brentonhouse** [comment]
Yea.. I did the same thing.   I should make that clearer in the docs.

**Comment by brentonhouse** [comment]
Updated docs and closing issue.
