### ISSUE TITLE
apple sign in module not returning userid on login event

### ISSUE THREAD

**Issue by mbilwar** [tidev/titanium-apple-sign-in#9]
Hi,

I am trying to get the userid and other details from apple sign in the module but its returning following details. am I missing something?

event: {"cancelled":true,"success":false,"bubbles":true,"type":"login","source":{},"cancelBubble":false}

tiapp.xml details
SDK: 8.2.1
tried with developer certificate and Adhoc certificate too but no success.
created identifiers too but nothing seems to work. 

Do I have to add a domain as well? there was an option to create Service ID and domain configuration?

Please help with more details. 

Thanks in advance! :)

**Comment by hansemannn** [comment]
This is not a module issue
